# Generated by Django 2.2.7 on 2019-12-07 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191205_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientmapping_child', to='home.Ingredient')),
                ('parent_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientmapping_parent', to='home.Ingredient')),
            ],
        ),
    ]
