# Generated by Django 2.2.7 on 2019-12-07 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ingredientmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productrecommendations_one', to='home.Product')),
                ('product_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productrecommendations_two', to='home.Product')),
            ],
        ),
    ]
