# Generated by Django 2.2.7 on 2019-11-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191125_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='not_applicable', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
